apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-k8s-deployment
  labels:
    app: hazelcast-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast-k8s-deployment
  template:
    metadata:
      labels:
        app: hazelcast-k8s-deployment
    spec:
      containers:
        - name: hazelcast-k8s-deployment
          image: naveenkrishiv/hazelcast-spboot
          env:
          - name: DATABASE_SERVER
            value: "jdbc:h2:mem:testdb" 
          ports:
            - name: http
              containerPort: 8080
            - name: multicast
              containerPort: 5701
              
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-k8s-deployment
  labels:
    app: hazelcast-k8s-deployment
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: hazelcast-k8s-deployment
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-spboot-service
spec:
  selector:
    app: hazelcast-k8s-deployment
  ports:
    - name: hazelcast
      port: 5701
  type: LoadBalancer